### PR TITLE
Patch critical security vulnerability in SharpZipLib

### PR DESCRIPTION
**Pull request by Kraegon**
## Changed

* Fixed critical security vulnerability in SharpZipLib package

### CODE REVIEW

**Review by henkery — CHANGES_REQUESTED** [review]
Looks good but cannot sign off as the CI didn't pass

**Review by henkery — APPROVED** [review]
LGTM

**Comment by jorismathijssen** [comment]
[Remove unit tests](https://github.com/Comfy-Corp/OpenLingo/pull/1/commits/bd235479b309d053b3514f83b7adf6e37606bca1) 

image

**Comment by Kraegon** [comment]
> [Remove unit tests](https://github.com/Comfy-Corp/OpenLingo/pull/1/commits/bd235479b309d053b3514f83b7adf6e37606bca1)
> 
> image

🤫

**Pull request merged**
